[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pa-tomography-xu-wang"
version = "0.1.0"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy"
]
